### ISSUE TITLE
publish 0.3.6

### ISSUE THREAD

**Issue by knownasilya** [Strider-CD/strider-node#10]

**Comment by doublerebel** [comment]
+1, this is now at 0.5.1 :)

Thanks for your work!

**Comment by knownasilya** [comment]
You can now update via the plugin manager, which doesn't need an npm
publish.

**Comment by doublerebel** [comment]
@knownasilya Yes, but on first run the default npm install doesn't include the latest versions of several plugins.  As a new user I didn't notice for days that my default plugins on a fresh install could be out of date.  Perhaps there should be a note in the install guide if this is intended behavior.

**Comment by knownasilya** [comment]
@doublerebel there has been some talk with @keyvanfatehi to do an auto update on strider start. This looks like the first request for that.

**Comment by doublerebel** [comment]
Autoupdate would be very useful, :+1: from me!
