### ISSUE TITLE
Updating strider-node plugin does not give me version 0.6.5

### ISSUE THREAD

**Issue by toddself** [Strider-CD/strider-node#22]
Running strider 1.6.6 and did the update plugin on strider-node.

Still running 0.3.5 (which seems to be the most recent published version?).

However, that comes with an ANCIENT npm that does not work for us (scoped modules).

When will 0.6.5 be published?  Would rather not have to manually update plugins.

**Comment by toddself** [comment]
Doing `npm i strider-cd/strider-node` fixes this, however it's really a non-optimal solution.

**Comment by knownasilya** [comment]
@toddself You can update it in the plugin manager

**Comment by toddself** [comment]
I did.

It was successul according to the logs, however on disk 0.3.5 was still installed with npm 1.3.35.

Even tried restarting strider to verify.

Plugin page no longer said an update was available.

**Comment by knownasilya** [comment]
@toddself are you running in Heroku or locally?

**Comment by knownasilya** [comment]
@toddself I just updated the npm module, but this should still work without that update using the plugin manager. NPM version 2+ is recommended.

**Comment by knownasilya** [comment]
Closing this. If you have any issues I can reopen.
