### ISSUE TITLE
Remove n

### ISSUE THREAD

**Issue by oliversalzburg** [Strider-CD/strider-node#24]
n is not compatible with Windows and it is only required when targeting a specific node/io version.

While I realize that this might be an important feature to some, it makes it impossible to work with Strider on Windows. And the dependency makes it impossible to even install the plugin, because of the [platform limitations in the `package.json`](https://github.com/tj/n/blob/master/package.json#L33-L35).

**Comment by knownasilya** [comment]
You can use the whatever option to just use your version on the system.

**Comment by oliversalzburg** [comment]
@knownasilya Yeah, that's what I'm doing. But when I try to update the `strider-node` plugin, it will try to `npm install`, which fails because `n` can't be installed on Windows.

**Comment by knownasilya** [comment]
@oliversalzburg sounds like something to bring up with the n maintainers, since it should be installable even if it's windows.

**Comment by knownasilya** [comment]
See if others are installable, like nvm, maybe we can switch.

**Comment by oliversalzburg** [comment]
@knownasilya The `n` maintainers are aware and are waiting for pull requests. Seems like a daunting task though.

**Comment by oliversalzburg** [comment]
I've removed the dependency, as `n` should be installed globally anyway. Now the package can be installed anywhere.
