### ISSUE TITLE
NODE_PATH broken

### ISSUE THREAD

**Issue by carlitux** [Strider-CD/strider-node#28]
I have this command to test

NODE_PATH=app:lib:frontend/javascript mocha

but not working on strider.

**Comment by knownasilya** [comment]
We use the `n` module, which doesn't honor `NODE_PATH`. See https://www.npmjs.com/package/n

**Comment by carlitux** [comment]
I read the doc and it doesn't say about the NODE_PATH. Commands run inside the project directory or there is a way to get the project directory?

**Comment by knownasilya** [comment]
`$PWD` will give you the current directory. 

What are you trying to do?

**Comment by carlitux** [comment]
@knownasilya sorry my mistake... Already NODE_PATH is used, I had in .gitignore a RE that those files was skipped.
