### ISSUE TITLE
Update npm version

### ISSUE THREAD

**Issue by xgalen** [Strider-CD/strider-node#30]
Maybe it is the moment to update the `npm` version or allow the upgrade to v3.x.x.

https://github.com/Strider-CD/strider-node/blob/master/package.json#L20

**Comment by knownasilya** [comment]
@xgalen would love it if you could test it with a PR :+1:

**Comment by xgalen** [comment]
@knownasilya one of the two tests is failing right now.

**Comment by bjrmatos** [comment]
please don't forget about npm@2 users :smile:

**Comment by xgalen** [comment]
@bjrmatos solved in commit [7a25656](7a25656)

**Comment by knownasilya** [comment]
Not sure that would solve it, since it would install the latest pretty much. Seems like the solution would be to select a version..

**Comment by oliversalzburg** [comment]
npm isn't really a dependency of this module. If you want to use a specific npm version, install it as a global module through the configuration of this module.
